### ISSUE TITLE
Please support firewalld

### ISSUE THREAD

**Issue by hyclak** [ewannema/es-fixer#2]
Please update to support firewalld in addition to iptables

**Comment by ewannema** [comment]
Something like this?

```yaml
yum:
  name: firewalld
  state: absent

yum:
  name: iptables
  state: present
```
